"""ADK web entry point for github_agent.

AUTO-GENERATED by scripts/generate_adk_agents.py — do not edit manually.
Edit agents-config/github_agent.yaml instead, then re-run the script.
"""

import sys
from pathlib import Path

# Ensure project root is on sys.path when loaded by `adk web`
_ROOT = Path(__file__).parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from dotenv import load_dotenv

load_dotenv()

from google.adk.agents import Agent

from app.agents.registry import get as get_agent_def
from app.tools.loader import load_tools


def create_agent() -> Agent:
    d = get_agent_def("github_agent")
    return Agent(
        name=d.name,
        model=d.model,
        description=d.description,
        instruction=d.instruction,
        tools=load_tools(d),
    )


# Required by `adk web`
root_agent = create_agent()
