"""Generate agents/ ADK web packages from agents-config/*.yaml.

Run this whenever you add or remove a YAML agent config:

    python scripts/generate_adk_agents.py

ADK web requires each agent to be a subdirectory with agent.py + root_agent.
This script auto-creates those files so you never write them manually.

The generated files are thin wrappers — all real config lives in agents-config/.
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
CONFIG_DIR = ROOT / "agents-config"
AGENTS_DIR = ROOT / "agents"

# Template for agents/<name>/agent.py
_AGENT_PY = '''\
"""ADK web entry point for {name}.

AUTO-GENERATED by scripts/generate_adk_agents.py — do not edit manually.
Edit agents-config/{name}.yaml instead, then re-run the script.
"""

import sys
from pathlib import Path

# Ensure project root is on sys.path when loaded by `adk web`
_ROOT = Path(__file__).parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from dotenv import load_dotenv

load_dotenv()

from google.adk.agents import Agent

from app.agents.registry import get as get_agent_def
from app.tools.loader import load_tools


def create_agent() -> Agent:
    d = get_agent_def("{name}")
    return Agent(
        name=d.name,
        model=d.model,
        description=d.description,
        instruction=d.instruction,
        tools=load_tools(d),
    )


# Required by `adk web`
root_agent = create_agent()
'''

_INIT_PY = '''\
"""ADK web package for {name}. AUTO-GENERATED — do not edit manually."""

from .agent import create_agent, root_agent

__all__ = ["create_agent", "root_agent"]
'''


def generate() -> None:
    configs = sorted(CONFIG_DIR.glob("*.yaml"))
    if not configs:
        print(f"No YAML files found in {CONFIG_DIR}")
        sys.exit(1)

    AGENTS_DIR.mkdir(exist_ok=True)
    (AGENTS_DIR / "__init__.py").write_text('"""ADK web agent packages. AUTO-GENERATED."""\n')

    generated = []
    for config_path in configs:
        with config_path.open() as fh:
            data = yaml.safe_load(fh)
        name = data.get("name")
        if not name:
            print(f"  SKIP {config_path.name} — missing 'name' field")
            continue

        agent_dir = AGENTS_DIR / name
        agent_dir.mkdir(exist_ok=True)
        (agent_dir / "agent.py").write_text(_AGENT_PY.format(name=name))
        (agent_dir / "__init__.py").write_text(_INIT_PY.format(name=name))
        generated.append(name)
        print(f"  OK   agents/{name}/")

    print(f"\nGenerated {len(generated)} agent package(s): {generated}")
    print("Run:  .venv/bin/adk web agents/")


if __name__ == "__main__":
    generate()
